name: Main

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 16.14.2

jobs:
  cypress:
    name: Cypress CI-CD Execution
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          always-auth: true
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - uses: cypress-io/github-action@v4
        with:
          command: npm run cypress:all
        env:
          TEST_USER: ${{ secrets.TEST_USER}}
          TEST_PASS: ${{ secrets.TEST_PASS}}
          
      - name: Upload cypress report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-report
          path: cypress/report/index.html